// src/shared/components/forms/FormSelect.tsx
'use client'

import { Controller, type FieldValues } from 'react-hook-form'
import { cn } from '@/shared/lib/utils'
import { FieldWrapper } from './FieldWrapper'
import type { FieldBaseProps, SelectOption } from './types'

export interface FormSelectProps<TValues extends FieldValues> extends FieldBaseProps<TValues> {
  options: SelectOption[]
  placeholder?: string
}

export function FormSelect<TValues extends FieldValues>({
  control,
  name,
  label,
  options,
  placeholder = 'Selecciona una opción',
  disabled,
  required,
  description,
  className,
}: FormSelectProps<TValues>) {
  return (
    <Controller
      control={control}
      name={name}
      render={({ field, fieldState }) => (
        <FieldWrapper
          label={label}
          error={fieldState.error?.message}
          description={description}
          required={required}
          className={className}
        >
          <select
            {...field}
            disabled={disabled}
            value={field.value ?? ''}
            className={cn(
              'h-11 w-full rounded-lg border border-input bg-card px-3.5 py-2 text-sm shadow-sm',
              'transition-colors duration-150',
              'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1',
              'disabled:cursor-not-allowed disabled:opacity-50',
              !field.value && 'text-muted-foreground',
              fieldState.error
                ? 'border-destructive focus-visible:ring-destructive/40'
                : 'hover:border-ring/40',
            )}
          >
            <option value="" disabled>
              {placeholder}
            </option>
            {options.map((opt) => (
              <option key={opt.value} value={opt.value} disabled={opt.disabled}>
                {opt.label}
              </option>
            ))}
          </select>
        </FieldWrapper>
      )}
    />
  )
}

// apps/pos-angular/src/app/shared/molecules/form-select.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core'
import { ControlContainer, FormGroupDirective, ReactiveFormsModule } from '@angular/forms'
import { FieldWrapperComponent } from './field-wrapper.component'

export interface FormSelectOption<T extends string | number = string> {
  value: T
  label: string
}

@Component({
  selector: 'mo-form-select',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'block' },
  imports: [ReactiveFormsModule, FieldWrapperComponent],
  viewProviders: [{ provide: ControlContainer, useExisting: FormGroupDirective }],
  template: `
    <mo-field-wrapper
      [label]="label()"
      [description]="description()"
      [error]="error()"
      [required]="required()"
    >
      <select [formControlName]="controlName()" [class]="selectClasses()">
        @if (placeholder()) {
          <option [ngValue]="''">{{ placeholder() }}</option>
        }
        @for (option of options(); track option.value) {
          <option [ngValue]="option.value">{{ option.label }}</option>
        }
      </select>
    </mo-field-wrapper>
  `,
})
export class FormSelectComponent {
  readonly controlName = input.required<string>()
  readonly options = input.required<FormSelectOption<string | number>[]>()
  readonly label = input<string | null>(null)
  readonly placeholder = input<string | null>('Selecciona una opcion')
  readonly description = input<string | null>(null)
  readonly required = input<boolean>(false)
  readonly error = input<string | null>(null)

  readonly selectClasses = computed(() =>
    [
      'h-11 w-full rounded-lg border bg-card px-3 py-2 text-sm shadow-sm',
      'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-1',
      this.error() ? 'border-destructive focus:ring-destructive/40' : 'border-input',
    ].join(' '),
  )
}
