// src/modules/inventory/components/KardexDialog.tsx
'use client'

import { useState, useEffect } from 'react'
import { Dialog } from '@/shared/components/ui/Dialog'
import { Button } from '@/shared/components/ui/Button'
import { formatShortDate, formatTime } from '@/shared/lib/format'
import { getKardexAction } from '../application/actions/inventory.actions'
import type { InventoryMovement } from '../domain/entities/inventory.entity'

const TIPO_LABELS: Record<string, { label: string; color: string }> = {
  entry:       { label: 'Entrada',   color: 'text-green-600' },
  sale_exit:   { label: 'Venta',     color: 'text-foreground' },
  adjustment:  { label: 'Ajuste',    color: 'text-primary' },
  void_return: { label: 'Anulación', color: 'text-muted-foreground' },
}

interface Props {
  productId: string
  productNombre: string
  onClose: () => void
}

export function KardexDialog({ productId, productNombre, onClose }: Props) {
  const [movements, setMovements] = useState<InventoryMovement[] | null>(null)

  useEffect(() => {
    getKardexAction(productId).then(setMovements)
  }, [productId])

  return (
    <Dialog open onClose={onClose} title={`Kardex — ${productNombre}`}>
      {movements === null ? (
        <div className="flex items-center justify-center py-12">
          <div className="h-5 w-5 animate-spin rounded-full border-2 border-primary border-t-transparent" />
        </div>
      ) : movements.length === 0 ? (
        <p className="py-8 text-center text-sm text-muted-foreground">Sin movimientos registrados.</p>
      ) : (
        <div className="max-h-[400px] overflow-y-auto">
          <table className="w-full text-sm">
            <thead className="sticky top-0 bg-card">
              <tr className="border-b">
                <th className="py-2 text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground">Fecha</th>
                <th className="py-2 text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground">Tipo</th>
                <th className="py-2 text-right text-xs font-semibold uppercase tracking-wide text-muted-foreground">Cantidad</th>
                <th className="py-2 text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground">Motivo</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {movements.map((m) => {
                const meta = TIPO_LABELS[m.tipo] ?? { label: m.tipo, color: 'text-foreground' }
                return (
                  <tr key={m.id}>
                    <td className="py-2.5 text-xs text-muted-foreground">
                      {formatShortDate(m.createdAt)} {formatTime(m.createdAt)}
                    </td>
                    <td className={`py-2.5 font-medium ${meta.color}`}>{meta.label}</td>
                    <td className={`py-2.5 text-right font-mono font-semibold tabular-nums ${m.cantidad > 0 ? 'text-green-600' : 'text-destructive'}`}>
                      {m.cantidad > 0 ? '+' : ''}{m.cantidad}
                    </td>
                    <td className="py-2.5 text-xs text-muted-foreground">
                      {m.motivo ?? '—'}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      )}
      <div className="mt-4 flex justify-end">
        <Button variant="outline" onClick={onClose}>Cerrar</Button>
      </div>
    </Dialog>
  )
}

// apps/pos-angular/src/app/features/inventory/kardex.dialog.ts
import {
  ChangeDetectionStrategy,
  Component,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core'
import { DialogComponent } from '../../shared/ui/dialog.component'
import { BadgeComponent } from '../../shared/ui/badge.component'
import { InventoryRepository } from './inventory.repository'
import { SessionService } from '../../core/auth/session.service'
import { formatTime, formatShortDate } from '@/shared/lib/format'
import type { InventoryMovement } from '@/modules/inventory/domain/entities/inventory.entity'

interface ProductSummary {
  id: string
  nombre: string
}

const TIPO_LABELS: Record<string, string> = {
  entry: 'Entrada',
  sale_exit: 'Venta',
  adjustment: 'Ajuste',
  void_return: 'Anulacion',
}

@Component({
  selector: 'mo-kardex-dialog',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DialogComponent, BadgeComponent],
  template: `
    <mo-dialog
      [open]="open()"
      title="Kardex"
      [description]="product()?.nombre ?? null"
      width="lg"
      (closed)="closed.emit()"
    >
      @if (loading()) {
        <p class="text-muted-foreground py-6 text-center text-sm">Cargando movimientos...</p>
      } @else if (loadError()) {
        <p class="text-destructive py-6 text-center text-sm">{{ loadError() }}</p>
      } @else if (movements().length === 0) {
        <p class="text-muted-foreground py-6 text-center text-sm">
          Sin movimientos registrados.
        </p>
      } @else {
        <div class="max-h-[60vh] overflow-y-auto">
          <table class="w-full text-sm">
            <thead class="bg-muted/50 text-muted-foreground sticky top-0 text-left text-xs uppercase tracking-wide">
              <tr>
                <th class="px-3 py-2">Fecha</th>
                <th class="px-3 py-2">Tipo</th>
                <th class="px-3 py-2 text-right">Cantidad</th>
                <th class="px-3 py-2">Motivo</th>
              </tr>
            </thead>
            <tbody class="divide-y">
              @for (mov of movements(); track mov.id) {
                <tr>
                  <td class="text-muted-foreground px-3 py-2 text-xs">
                    {{ shortDate(mov.createdAt) }} · {{ time(mov.createdAt) }}
                  </td>
                  <td class="px-3 py-2">
                    <mo-badge [variant]="badgeVariant(mov.tipo)">{{ tipoLabel(mov.tipo) }}</mo-badge>
                  </td>
                  <td
                    class="px-3 py-2 text-right tabular-nums"
                    [class.text-emerald-600]="mov.cantidad > 0"
                    [class.text-destructive]="mov.cantidad < 0"
                  >
                    {{ mov.cantidad > 0 ? '+' : '' }}{{ mov.cantidad }}
                  </td>
                  <td class="text-muted-foreground px-3 py-2 text-xs">{{ mov.motivo ?? '—' }}</td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }
    </mo-dialog>
  `,
})
export class KardexDialog {
  private readonly repo = inject(InventoryRepository)
  private readonly session = inject(SessionService)

  readonly open = input<boolean>(false)
  readonly product = input<ProductSummary | null>(null)
  readonly closed = output<void>()

  readonly movements = signal<InventoryMovement[]>([])
  readonly loading = signal(false)
  readonly loadError = signal<string | null>(null)

  constructor() {
    effect(() => {
      const product = this.product()
      if (this.open() && product) {
        void this.load(product.id)
      }
    })
  }

  shortDate(d: Date): string {
    return formatShortDate(d)
  }

  time(d: Date): string {
    return formatTime(d)
  }

  tipoLabel(tipo: string): string {
    return TIPO_LABELS[tipo] ?? tipo
  }

  badgeVariant(tipo: string): 'default' | 'success' | 'warning' | 'destructive' {
    if (tipo === 'entry') return 'success'
    if (tipo === 'sale_exit') return 'default'
    if (tipo === 'adjustment') return 'warning'
    if (tipo === 'void_return') return 'destructive'
    return 'default'
  }

  async load(productId: string): Promise<void> {
    this.loading.set(true)
    this.loadError.set(null)
    try {
      const auth = await this.session.getAuthContext()
      if (!auth) throw new Error('No autenticado')
      const list = await this.repo.getKardex(productId, auth.tiendaId)
      this.movements.set(list)
    } catch (error) {
      this.loadError.set(error instanceof Error ? error.message : 'Error al cargar kardex')
    } finally {
      this.loading.set(false)
    }
  }
}
