// apps/pos-angular/src/app/features/products/product-form.dialog.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core'
import { getErrorMessage } from '@/shared/lib/error-message'
import { ReactiveFormsModule } from '@angular/forms'
import { DialogComponent } from '../../shared/ui/dialog.component'
import { ButtonComponent } from '../../shared/ui/button.component'
import { FormInputComponent } from '../../shared/forms/form-input.component'
import { FormCurrencyInputComponent } from '../../shared/forms/form-currency-input.component'
import { FormNumberInputComponent } from '../../shared/forms/form-number-input.component'
import { FormSelectComponent, type FormSelectOption } from '../../shared/forms/form-select.component'
import { FormCheckboxComponent } from '../../shared/forms/form-checkbox.component'
import { FormTextareaComponent } from '../../shared/forms/form-textarea.component'
import { FormErrorComponent } from '../../shared/forms/form-error.component'
import { ProductFormPresenter } from './product-form.presenter'
import { productFormMapper } from '@/modules/products/forms/product-form.mapper'
import type { Product, Categoria } from '@/modules/products/domain/entities/product.entity'
import { ProductsRepository } from './products.repository'
import { SessionService } from '../../core/auth/session.service'
import { ToastService } from '../../shared/feedback/toast.service'

const TIPO_OPTIONS: FormSelectOption<string>[] = [
  { value: 'simple', label: 'Simple' },
  { value: 'prepared', label: 'Preparado' },
  { value: 'ingredient', label: 'Ingrediente' },
]

const IVA_OPTIONS: FormSelectOption<number>[] = [
  { value: 0, label: '0% (exento)' },
  { value: 5, label: '5%' },
  { value: 19, label: '19%' },
]

@Component({
  selector: 'mo-product-form-dialog',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [ProductFormPresenter],
  imports: [
    ReactiveFormsModule,
    DialogComponent,
    ButtonComponent,
    FormInputComponent,
    FormCurrencyInputComponent,
    FormNumberInputComponent,
    FormSelectComponent,
    FormCheckboxComponent,
    FormTextareaComponent,
    FormErrorComponent,
  ],
  template: `
    <mo-dialog
      [open]="open()"
      [title]="dialogTitle()"
      [busy]="saving()"
      width="lg"
      (closed)="onClose()"
    >
      <form [formGroup]="presenter.form" (ngSubmit)="submit()" class="space-y-4">
        <mo-form-input
          controlName="nombre"
          label="Nombre"
          [required]="true"
          [error]="presenter.errors().nombre ?? null"
        />

        <div class="grid gap-4 sm:grid-cols-2">
          <mo-form-input
            controlName="sku"
            label="SKU"
            placeholder="WHY-001"
            [error]="presenter.errors().sku ?? null"
          />
          <mo-form-input
            controlName="codigoBarras"
            label="Codigo de barras"
            placeholder="7700000000001"
            [error]="presenter.errors().codigoBarras ?? null"
          />
        </div>

        <div class="grid gap-4 sm:grid-cols-2">
          <mo-form-select
            controlName="categoriaId"
            label="Categoria"
            placeholder="Sin categoria"
            [options]="categoriaOptions()"
            [error]="presenter.errors().categoriaId ?? null"
          />
          <mo-form-select
            controlName="tipo"
            label="Tipo"
            [placeholder]="null"
            [options]="tipoOptions"
            [error]="presenter.errors().tipo ?? null"
          />
        </div>

        <div class="space-y-4 rounded-xl border p-4">
          <div>
            <h3 class="text-sm font-semibold">Información para recomendar</h3>
            <p class="text-muted-foreground mt-1 text-xs">
              Usa la ficha oficial del fabricante como fuente.
            </p>
          </div>
          <mo-form-textarea
            controlName="paraQueSirve"
            label="Para qué sirve"
            placeholder="Ej. Apoya la recuperación muscular y ayuda a completar la ingesta diaria de proteína."
            description="Resume la finalidad y los beneficios principales sin promesas médicas."
            [rows]="3"
            [error]="presenter.errors().paraQueSirve ?? null"
          />
          <mo-form-textarea
            controlName="recomendadoPara"
            label="A quién se recomienda"
            placeholder="Ej. Personas activas que buscan complementar su consumo diario de proteína."
            description="Describe el perfil de cliente adecuado y evita diagnósticos o prescripciones."
            [rows]="3"
            [error]="presenter.errors().recomendadoPara ?? null"
          />
        </div>

        <div class="grid gap-4 sm:grid-cols-2">
          <mo-form-currency-input
            controlName="precioVenta"
            label="Precio de venta"
            [required]="true"
            [error]="presenter.errors().precioVenta ?? null"
          />
          <mo-form-currency-input
            controlName="costo"
            label="Costo"
            [error]="presenter.errors().costo ?? null"
          />
        </div>

        <div class="grid gap-4 sm:grid-cols-3">
          <mo-form-select
            controlName="ivaTasa"
            label="IVA"
            [placeholder]="null"
            [options]="ivaOptions"
            [error]="presenter.errors().ivaTasa ?? null"
          />
          <mo-form-input
            controlName="unidad"
            label="Unidad"
            placeholder="und, kg, ml"
            [error]="presenter.errors().unidad ?? null"
          />
          <mo-form-number-input
            controlName="stockMinimo"
            label="Stock minimo"
            [min]="0"
            [error]="presenter.errors().stockMinimo ?? null"
          />
        </div>

        <mo-form-checkbox controlName="isActive" label="Producto activo" />

        <mo-form-error [message]="presenter.errors().root ?? null" />

        <div class="flex justify-end gap-2 pt-2">
          <mo-button variant="outline" type="button" [disabled]="saving()" (click)="onClose()">
            Cancelar
          </mo-button>
          <mo-button type="submit" [loading]="saving()" loadingText="Guardando...">
            {{ product() ? 'Guardar cambios' : 'Crear producto' }}
          </mo-button>
        </div>
      </form>
    </mo-dialog>
  `,
})
export class ProductFormDialog {
  private readonly repo = inject(ProductsRepository)
  private readonly session = inject(SessionService)
  private readonly toast = inject(ToastService)

  readonly presenter = inject(ProductFormPresenter)
  readonly tipoOptions = TIPO_OPTIONS
  readonly ivaOptions = IVA_OPTIONS

  readonly open = input<boolean>(false)
  readonly product = input<Product | null>(null)
  readonly categorias = input<Categoria[]>([])

  readonly closed = output<void>()
  readonly saved = output<Product>()

  readonly saving = signal(false)

  readonly categoriaOptions = computed<FormSelectOption<string>[]>(() =>
    this.categorias().map((c) => ({ value: c.id, label: c.nombre })),
  )

  readonly dialogTitle = computed(() => (this.product() ? 'Editar producto' : 'Nuevo producto'))

  constructor() {
    effect(() => {
      if (this.open()) {
        this.presenter.reset(productFormMapper.toFormValue(this.product()))
      }
    })
  }

  async submit(): Promise<void> {
    if (this.saving()) return
    const value = this.presenter.validate()
    if (!value) return

    const auth = await this.session.getAuthContext()
    if (!auth) {
      this.presenter.setRootError('Sesion expirada')
      return
    }

    this.saving.set(true)
    this.presenter.form.disable({ emitEvent: false })

    try {
      const product = this.product()
      const result = product
        ? await this.repo.updateProduct(
            product.id,
            auth.tiendaId,
            productFormMapper.toUpdatePayload(value),
          )
        : await this.repo.createProduct(
            productFormMapper.toCreatePayload(value, auth.tiendaId),
          )

      this.toast.success(product ? 'Producto actualizado' : 'Producto creado')
      this.saved.emit(result)
      this.closed.emit()
    } catch (error) {
      this.presenter.setRootError(getErrorMessage(error, 'Error al guardar'))
    } finally {
      this.saving.set(false)
      this.presenter.form.enable({ emitEvent: false })
    }
  }

  onClose(): void {
    if (this.saving()) return
    this.closed.emit()
  }
}

// src/modules/products/components/ProductFormDialog.tsx
'use client'

import { useEffect } from 'react'
import { Dialog } from '@/shared/components/ui/Dialog'
import { Button } from '@/shared/components/ui/Button'
import {
  FormInput,
  FormSelect,
  FormNumberInput,
  FormCurrencyInput,
  FormCheckbox,
  SubmitButton,
  FormError,
} from '@/shared/components/forms'
import { useActionFeedback } from '@/shared/hooks/use-action-feedback'
import { useProductForm } from '../hooks/use-product-form'
import type { Product, Categoria } from '../domain/entities/product.entity'
import type { SelectOption } from '@/shared/components/forms'

interface ProductFormDialogProps {
  open: boolean
  onClose: () => void
  product?: Product | null
  categorias: Categoria[]
}

const TIPO_OPTIONS: SelectOption[] = [
  { value: 'simple',     label: 'Simple' },
  { value: 'prepared',   label: 'Preparado (batido)' },
  { value: 'ingredient', label: 'Ingrediente' },
]

const IVA_OPTIONS: SelectOption[] = [
  { value: '0',  label: '0% — Exento' },
  { value: '5',  label: '5%' },
  { value: '19', label: '19%' },
]

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-[11px] font-bold uppercase tracking-widest text-muted-foreground">
      {children}
    </p>
  )
}

export function ProductFormDialog({ open, onClose, product, categorias }: ProductFormDialogProps) {
  const { form, formAction, isPending, serverError, message, isEditMode, reset } = useProductForm({ product })

  useEffect(() => {
    if (open) reset(product)
  }, [open, product, reset])

  useActionFeedback({
    state: { error: serverError, message },
    pending: isPending,
    onSuccess: onClose,
    successMessage: isEditMode ? 'Producto actualizado correctamente' : 'Producto creado correctamente',
    showErrorToast: true,
  })

  const categoriaOptions: SelectOption[] = [
    { value: '', label: 'Sin categoría' },
    ...categorias
      .filter((c) => c.isActive)
      .map((c) => ({ value: c.id, label: c.nombre })),
  ]

  return (
    <Dialog
      open={open}
      onClose={onClose}
      title={isEditMode ? 'Editar producto' : 'Nuevo producto'}
      className="max-w-2xl"
      isBusy={isPending}
    >
      <form action={formAction} className="space-y-6">

        {/* ── Identificación ─────────────────────────────────── */}
        <div className="space-y-4">
          <SectionLabel>Identificación</SectionLabel>
          <div className="grid grid-cols-2 gap-4">
            <FormInput
              control={form.control}
              name="nombre"
              label="Nombre"
              placeholder="Ej: Whey Protein 2Kg"
              required
              className="col-span-2 sm:col-span-1"
            />
            <FormInput
              control={form.control}
              name="sku"
              label="SKU"
              placeholder="Ej: WHY-VAN-2KG"
              autoComplete="off"
            />
          </div>
          <FormInput
            control={form.control}
            name="codigoBarras"
            label="Código de barras"
            placeholder="7501000000000"
            autoComplete="off"
          />
        </div>

        {/* ── Clasificación ──────────────────────────────────── */}
        <div className="space-y-4 border-t pt-5">
          <SectionLabel>Clasificación</SectionLabel>
          <div className="grid grid-cols-2 gap-4">
            <FormSelect
              control={form.control}
              name="tipo"
              label="Tipo"
              options={TIPO_OPTIONS}
              required
            />
            <FormSelect
              control={form.control}
              name="categoriaId"
              label="Categoría"
              options={categoriaOptions}
              placeholder="Sin categoría"
            />
          </div>
          <FormInput
            control={form.control}
            name="unidad"
            label="Unidad"
            placeholder="und, kg, ml…"
            required
          />
        </div>

        {/* ── Precios y tributos ─────────────────────────────── */}
        <div className="space-y-4 border-t pt-5">
          <SectionLabel>Precios y tributos</SectionLabel>
          <div className="grid grid-cols-3 gap-4">
            <FormCurrencyInput
              control={form.control}
              name="precioVenta"
              label="Precio de venta"
              required
            />
            <FormCurrencyInput
              control={form.control}
              name="costo"
              label="Costo"
            />
            <FormSelect
              control={form.control}
              name="ivaTasa"
              label="IVA"
              options={IVA_OPTIONS}
              required
            />
          </div>
        </div>

        {/* ── Control de inventario ──────────────────────────── */}
        <div className="space-y-4 border-t pt-5">
          <SectionLabel>Inventario</SectionLabel>
          <div className="flex items-end gap-6">
            <FormNumberInput
              control={form.control}
              name="stockMinimo"
              label="Stock mínimo"
              placeholder="0"
              className="w-36"
            />
            <div className="pb-1">
              <FormCheckbox
                control={form.control}
                name="isActive"
                label="Producto activo"
              />
            </div>
          </div>
        </div>

        {serverError && <FormError message={serverError} />}

        {/* Footer */}
        <div className="flex justify-end gap-3 border-t pt-4">
          <Button type="button" variant="outline" onClick={onClose} disabled={isPending}>
            Cancelar
          </Button>
          <SubmitButton isLoading={isPending} loadingText="Guardando…">
            {isEditMode ? 'Guardar cambios' : 'Crear producto'}
          </SubmitButton>
        </div>
      </form>
    </Dialog>
  )
}
