// src/shared/components/forms/FormTextarea.tsx
'use client'

import { Controller, type FieldValues } from 'react-hook-form'
import { cn } from '@/shared/lib/utils'
import { FieldWrapper } from './FieldWrapper'
import type { FieldBaseProps } from './types'

export interface FormTextareaProps<TValues extends FieldValues> extends FieldBaseProps<TValues> {
  placeholder?: string
  rows?: number
  maxLength?: number
  resize?: 'none' | 'vertical' | 'horizontal' | 'both'
}

export function FormTextarea<TValues extends FieldValues>({
  control,
  name,
  label,
  placeholder,
  rows = 3,
  disabled,
  required,
  description,
  maxLength,
  resize = 'vertical',
  className,
}: FormTextareaProps<TValues>) {
  const resizeClass = {
    none: 'resize-none',
    vertical: 'resize-y',
    horizontal: 'resize-x',
    both: 'resize',
  }[resize]

  return (
    <Controller
      control={control}
      name={name}
      render={({ field, fieldState }) => (
        <FieldWrapper
          label={label}
          error={fieldState.error?.message}
          description={description}
          required={required}
          className={className}
        >
          <textarea
            {...field}
            placeholder={placeholder}
            rows={rows}
            disabled={disabled}
            maxLength={maxLength}
            value={field.value ?? ''}
            className={cn(
              'w-full rounded-md border border-input bg-background px-3 py-2 text-sm',
              'placeholder:text-muted-foreground',
              'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1',
              'disabled:cursor-not-allowed disabled:opacity-50',
              resizeClass,
              fieldState.error && 'border-destructive focus-visible:ring-destructive',
            )}
          />
        </FieldWrapper>
      )}
    />
  )
}

// apps/pos-angular/src/app/shared/forms/form-textarea.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core'
import { ControlContainer, FormGroupDirective, ReactiveFormsModule } from '@angular/forms'
import { FieldWrapperComponent } from './field-wrapper.component'

@Component({
  selector: 'mo-form-textarea',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, FieldWrapperComponent],
  viewProviders: [{ provide: ControlContainer, useExisting: FormGroupDirective }],
  template: `
    <mo-field-wrapper
      [label]="label()"
      [description]="description()"
      [error]="error()"
      [required]="required()"
    >
      <textarea
        [formControlName]="controlName()"
        [placeholder]="placeholder()"
        [rows]="rows()"
        [class]="textareaClasses()"
      ></textarea>
    </mo-field-wrapper>
  `,
})
export class FormTextareaComponent {
  readonly controlName = input.required<string>()
  readonly label = input<string | null>(null)
  readonly placeholder = input<string>('')
  readonly description = input<string | null>(null)
  readonly required = input<boolean>(false)
  readonly error = input<string | null>(null)
  readonly rows = input<number>(3)

  readonly textareaClasses = computed(() =>
    [
      'w-full rounded-lg border bg-card px-3 py-2 text-sm shadow-sm',
      'placeholder:text-muted-foreground/60',
      'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-1',
      this.error() ? 'border-destructive focus:ring-destructive/40' : 'border-input',
    ].join(' '),
  )
}
