// src/shared/components/forms/FormInput.tsx
'use client'

import { Controller, type FieldValues } from 'react-hook-form'
import { cn } from '@/shared/lib/utils'
import { FieldWrapper } from './FieldWrapper'
import type { FieldBaseProps } from './types'

export interface FormInputProps<TValues extends FieldValues> extends FieldBaseProps<TValues> {
  placeholder?: string
  type?: 'text' | 'email' | 'password' | 'search' | 'tel' | 'url'
  autoComplete?: string
  maxLength?: number
}

/**
 * Campo de texto genérico.
 * Usa internamente Controller de RHF — no expone `register` al módulo.
 */
export function FormInput<TValues extends FieldValues>({
  control,
  name,
  label,
  placeholder,
  type = 'text',
  disabled,
  required,
  description,
  autoComplete,
  maxLength,
  className,
}: FormInputProps<TValues>) {
  return (
    <Controller
      control={control}
      name={name}
      render={({ field, fieldState }) => (
        <FieldWrapper
          label={label}
          error={fieldState.error?.message}
          description={description}
          required={required}
          className={className}
        >
          <input
            {...field}
            type={type}
            placeholder={placeholder}
            disabled={disabled}
            autoComplete={autoComplete}
            maxLength={maxLength}
            value={field.value ?? ''}
            className={cn(
              'h-11 w-full rounded-lg border border-input bg-card px-3.5 py-2 text-sm shadow-sm',
              'placeholder:text-muted-foreground/60',
              'transition-colors duration-150',
              'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1',
              'disabled:cursor-not-allowed disabled:opacity-50',
              fieldState.error
                ? 'border-destructive focus-visible:ring-destructive/40'
                : 'hover:border-ring/40',
            )}
          />
        </FieldWrapper>
      )}
    />
  )
}

// apps/pos-angular/src/app/shared/forms/form-input.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core'
import { ControlContainer, FormGroupDirective, ReactiveFormsModule } from '@angular/forms'
import { FieldWrapperComponent } from './field-wrapper.component'

@Component({
  selector: 'mo-form-input',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, FieldWrapperComponent],
  viewProviders: [{ provide: ControlContainer, useExisting: FormGroupDirective }],
  template: `
    <mo-field-wrapper
      [label]="label()"
      [description]="description()"
      [error]="error()"
      [required]="required()"
    >
      <input
        [type]="type()"
        [formControlName]="controlName()"
        [placeholder]="placeholder()"
        [autocomplete]="autocomplete()"
        [attr.maxlength]="maxLength()"
        [class]="inputClasses()"
      />
    </mo-field-wrapper>
  `,
})
export class FormInputComponent {
  readonly controlName = input.required<string>()
  readonly label = input<string | null>(null)
  readonly type = input<'text' | 'email' | 'password' | 'search' | 'tel' | 'url'>('text')
  readonly placeholder = input<string>('')
  readonly autocomplete = input<string>('off')
  readonly maxLength = input<number | null>(null)
  readonly description = input<string | null>(null)
  readonly required = input<boolean>(false)
  readonly error = input<string | null>(null)

  readonly inputClasses = computed(() =>
    [
      'h-11 w-full rounded-lg border bg-card px-3.5 py-2 text-sm shadow-sm',
      'placeholder:text-muted-foreground/60',
      'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-1',
      'disabled:cursor-not-allowed disabled:opacity-50',
      this.error() ? 'border-destructive focus:ring-destructive/40' : 'border-input',
    ].join(' '),
  )
}
