// src/shared/components/forms/FormError.tsx
'use client'

interface FormErrorProps {
  message?: string
}

/**
 * Muestra el error raíz del formulario (errores del servidor).
 * Úsalo junto con form.setError('root', { message: '...' })
 *
 * Uso:
 *   <FormError message={form.formState.errors.root?.message} />
 */
export function FormError({ message }: FormErrorProps) {
  if (!message) return null

  return (
    <div
      role="alert"
      className="rounded-md border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive"
    >
      {message}
    </div>
  )
}

// apps/pos-angular/src/app/shared/forms/form-error.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core'

@Component({
  selector: 'mo-form-error',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (message()) {
      <div
        role="alert"
        class="border-destructive/30 bg-destructive/10 text-destructive rounded-md border px-4 py-3 text-sm"
      >
        {{ message() }}
      </div>
    }
  `,
})
export class FormErrorComponent {
  readonly message = input<string | null>(null)
}
