// src/shared/components/forms/FormNumberInput.tsx
'use client'

import { Controller, type FieldValues } from 'react-hook-form'
import { cn } from '@/shared/lib/utils'
import { FieldWrapper } from './FieldWrapper'
import type { FieldBaseProps } from './types'

export interface FormNumberInputProps<TValues extends FieldValues> extends FieldBaseProps<TValues> {
  placeholder?: string
  min?: number
  max?: number
  step?: number
}

/**
 * Campo numérico. Almacena el valor como number en el formulario.
 * Para valores monetarios usa FormCurrencyInput.
 */
export function FormNumberInput<TValues extends FieldValues>({
  control,
  name,
  label,
  placeholder,
  min,
  max,
  step = 1,
  disabled,
  required,
  description,
  className,
}: FormNumberInputProps<TValues>) {
  return (
    <Controller
      control={control}
      name={name}
      render={({ field, fieldState }) => (
        <FieldWrapper
          label={label}
          error={fieldState.error?.message}
          description={description}
          required={required}
          className={className}
        >
          <input
            type="number"
            placeholder={placeholder}
            disabled={disabled}
            min={min}
            max={max}
            step={step}
            value={field.value ?? ''}
            onChange={(e) => {
              const val = e.target.value
              field.onChange(val === '' ? undefined : Number(val))
            }}
            onBlur={field.onBlur}
            name={field.name}
            ref={field.ref}
            className={cn(
              'w-full rounded-md border border-input bg-background px-3 py-2 text-sm',
              'placeholder:text-muted-foreground',
              'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1',
              'disabled:cursor-not-allowed disabled:opacity-50',
              '[appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none',
              fieldState.error && 'border-destructive focus-visible:ring-destructive',
            )}
          />
        </FieldWrapper>
      )}
    />
  )
}

// apps/pos-angular/src/app/shared/forms/form-number-input.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core'
import { ControlContainer, FormGroupDirective, ReactiveFormsModule } from '@angular/forms'
import { FieldWrapperComponent } from './field-wrapper.component'

@Component({
  selector: 'mo-form-number-input',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, FieldWrapperComponent],
  viewProviders: [{ provide: ControlContainer, useExisting: FormGroupDirective }],
  template: `
    <mo-field-wrapper
      [label]="label()"
      [description]="description()"
      [error]="error()"
      [required]="required()"
    >
      <input
        type="number"
        inputmode="numeric"
        [formControlName]="controlName()"
        [placeholder]="placeholder()"
        [attr.min]="min()"
        [attr.max]="max()"
        [attr.step]="step()"
        [class]="inputClasses()"
      />
    </mo-field-wrapper>
  `,
})
export class FormNumberInputComponent {
  readonly controlName = input.required<string>()
  readonly label = input<string | null>(null)
  readonly placeholder = input<string>('')
  readonly description = input<string | null>(null)
  readonly required = input<boolean>(false)
  readonly error = input<string | null>(null)
  readonly min = input<number | null>(0)
  readonly max = input<number | null>(null)
  readonly step = input<number | string>('1')

  readonly inputClasses = computed(() =>
    [
      'h-11 w-full rounded-lg border bg-card px-3.5 py-2 text-sm shadow-sm tabular-nums',
      'placeholder:text-muted-foreground/60',
      'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-1',
      'disabled:cursor-not-allowed disabled:opacity-50',
      this.error() ? 'border-destructive focus:ring-destructive/40' : 'border-input',
    ].join(' '),
  )
}
